"""Add created_at attributes in PostVote and CommentVote models

Revision ID: 32b90642b62f
Revises: 00d67b475b39
Create Date: 2024-10-11 16:41:28.153821

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32b90642b62f'
down_revision = '00d67b475b39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment_votes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('post_votes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post_votes', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    with op.batch_alter_table('comment_votes', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
