"""creating the post_stats table

Revision ID: 37e6c32de134
Revises: 4774a04d38ae
Create Date: 2023-11-11 23:15:28.337243

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37e6c32de134'
down_revision = '4774a04d38ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('comments_count', sa.Integer(), nullable=True),
    sa.Column('bookmarks_count', sa.Integer(), nullable=True),
    sa.Column('upvotes_count', sa.Integer(), nullable=True),
    sa.Column('downvotes_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('post_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post_stats')
    # ### end Alembic commands ###
