"""creating the community_stats table

Revision ID: 4774a04d38ae
Revises: f75ed89bbe09
Create Date: 2023-11-11 23:14:36.251084

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4774a04d38ae'
down_revision = 'f75ed89bbe09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('community_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('community_id', sa.Integer(), nullable=True),
    sa.Column('posts_count', sa.Integer(), nullable=True),
    sa.Column('comments_count', sa.Integer(), nullable=True),
    sa.Column('subscribers_count', sa.Integer(), nullable=True),
    sa.Column('moderators_count', sa.Integer(), nullable=True),
    sa.Column('banned_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['community_id'], ['communities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('community_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('community_stats')
    # ### end Alembic commands ###
