"""creating the community_moderators table

Revision ID: 556bb803cd53
Revises: 260ae5e8ac71
Create Date: 2023-09-03 01:37:48.039636

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '556bb803cd53'
down_revision = '260ae5e8ac71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('community_moderators',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('community_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['community_id'], ['communities.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('community_moderators')
    # ### end Alembic commands ###
