"""creating the post_votes table

Revision ID: 57807e9429bb
Revises: 4fdf1eb6e707
Create Date: 2023-09-09 23:24:39.177764

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57807e9429bb'
down_revision = '4fdf1eb6e707'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_votes',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('direction', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'post_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post_votes')
    # ### end Alembic commands ###
